package shagejack.minecraftology;

import shagejack.minecraftology.client.data.Color;

public class Reference {
    public static final String MOD_ID = "minecraftology";
    public static final String MOD_NAME = "Minecraftology";
    public static final String VERSION = "@VERSION@";
    public static final String VERSION_DATE = "@DATE@";
    public static final String GUI_FACTORY_CLASS = "shagejack.minecraftology.gui.GuiConfigFactory";
    public static final String DEPENDENCIES = "";
    public static final String CHANNEL_NAME = "mcl_channel";
    public static final String CHANNEL_GUI_NAME = CHANNEL_NAME + ":gui";
    public static final byte MODE_REDSTONE_NONE = 2;
    public static final byte MODE_REDSTONE_HIGH = 1;
    public static final byte MODE_REDSTONE_LOW = 0;
    public static final String PATH_GFX = MOD_ID + ":textures/";
    public static final String PATH_WORLD_TEXTURES = PATH_GFX + "world/";
    public static final String PATH_ARMOR = PATH_GFX + "armor/";
    public static final String PATH_PARTICLE = PATH_GFX + "particle/";
    public static final String PATH_GUI = PATH_GFX + "gui/";
    public static final String PATH_BLOCKS = PATH_GFX + "blocks/";
    public static final String PATH_FX = PATH_GFX + "fx/";
    public static final String PATH_SHADERS = MOD_ID + ":shaders/";
    public static final String PATH_ELEMENTS = PATH_GUI + "elements/";
    public static final String PATH_ICON = PATH_GUI + "icons/";
    public static final String PATH_ENTITIES = PATH_GFX + "entities/";
    public static final String PATH_ITEM = PATH_GFX + "items/";
    public static final String PATH_GUI_ITEM = PATH_GUI + "items/";
    public static final String PATH_MODEL = MOD_ID + ":models/";
    public static final String PATH_MODEL_BLOCKS = PATH_MODEL + "block/";
    public static final String PATH_MODEL_ITEMS = PATH_MODEL + "item/";
    public static final String PATH_SOUNDS = MOD_ID + ":sounds/";
    public static final String PATH_SOUNDS_BLOCKS = PATH_SOUNDS + "blocks/";
    public static final String PATH_INFO = MOD_ID + ":info/";
    public static final String TEXTURE_ARROW_PROGRESS = PATH_ELEMENTS + "progress_arrow_right.png";
    public static final String TEXTURE_FE_METER = PATH_ELEMENTS + "fe.png";
    public static final Color COLOR_WHITE = new Color(255, 255, 255);
    public static final Color COLOR_MCL = new Color(191, 228, 230);
    public static final Color COLOR_HOLO = new Color(169, 226, 251);
    public static final Color COLOR_YELLOW_STRIPES = new Color(254, 203, 4);
    public static final Color COLOR_HOLO_RED = new Color(230, 80, 20);
    public static final Color COLOR_HOLO_GREEN = new Color(24, 207, 0);
    public static final Color COLOR_HOLO_YELLOW = new Color(252, 223, 116);
    public static final Color COLOR_HOLO_PURPLE = new Color(116, 23, 230);
    public static final Color COLOR_GUI_NORMAL = new Color(62, 81, 84);
    public static final Color COLOR_GUI_LIGHT = new Color(100, 113, 136);
    public static final Color COLOR_GUI_LIGHTER = new Color(139, 126, 168);
    public static final Color COLOR_GUI_DARK = new Color(44, 54, 52);
    public static final Color COLOR_GUI_DARKER = new Color(34, 40, 37);
    public static final Color COLOR_GUI_ENERGY = new Color(224, 0, 0);
}
